# Copyright (C) 2022 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later
name: partial_gcnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1.1
  - matplotlib
  - notebook
  - numpy=1.21.0
  - pandas=1.2.5
  - pillow=8.3.1
  - pip=21.1.3
  - python=3.8.10
  - pytorch=1.9.0
  - torchvision=0.10.0
  - typing_extensions
  - pip:
    - configparser
    - hydra-core
    - importlib-resources
    - omegaconf
    - pathtools
    - pyyaml
    - tqdm
    - urllib3
    - wandb
